"""
16S Analyzer Configuration
Auto-generated by setup.sh — edit as needed.
"""
import os
from pathlib import Path

# --- Paths ---
PROJECT_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_DIR / "data"
UPLOAD_DIR = DATA_DIR / "uploads"
DATASET_DIR = DATA_DIR / "datasets"
COMBINED_DIR = DATA_DIR / "combined"
EXPORT_DIR = DATA_DIR / "exports"
PICRUST2_RUNS_DIR = DATA_DIR / "picrust2_runs"
REFERENCE_DIR = DATA_DIR / "references"
SRA_CACHE_DIR = DATA_DIR / "sra_cache"
R_SCRIPTS_DIR = PROJECT_DIR / "r_scripts"

# --- Database ---
_DB_PATH = os.environ.get("DATABASE_PATH", str(PROJECT_DIR / "microbiome.db"))
DATABASE_URL = f"sqlite:///{_DB_PATH}"

# --- SILVA 138.1 ---
SILVA_TRAIN_SET = REFERENCE_DIR / "silva_nr99_v138.1_train_set.fa.gz"
SILVA_SPECIES = REFERENCE_DIR / "silva_species_assignment_v138.1.fa.gz"
SILVA_SPECIES_TRAIN_SET = REFERENCE_DIR / "silva_nr99_v138.1_wSpecies_train_set.fa.gz"
# Minimum identity for vsearch species fallback on full-length (long-read) ASVs
LONGREAD_SPECIES_MIN_ID = 0.99

# --- Conda ---
CONDA_BASE = Path(os.environ.get("CONDA_BASE", Path.home() / "miniforge3"))
CONDA_ENV_NAME = "microbiome_16S"
DADA2_ENV_NAME = "dada2_16S"
ANALYSIS_ENV_NAME = "analysis_16S"
# maaslin2_16S is a separate env for MaAsLin2/LinDA/vegan (R version conflicts).
# Falls back to analysis_16S for older installations that have everything in one env.
MAASLIN2_ENV_NAME = (
    "maaslin2_16S" if (CONDA_BASE / "envs" / "maaslin2_16S").exists()
    else "analysis_16S"
)
PICRUST2_ENV_NAME = "picrust2_16S"

# Map R script filenames to the conda env that has their dependencies.
_R_SCRIPT_ENV_MAP = {
    "run_dada2.R": DADA2_ENV_NAME,
    "run_taxonomy.R": DADA2_ENV_NAME,
    "run_ancombc.R": ANALYSIS_ENV_NAME,
    "run_deseq2.R": ANALYSIS_ENV_NAME,
    "run_aldex2.R": ANALYSIS_ENV_NAME,
    "run_linda.R": MAASLIN2_ENV_NAME,
    "run_maaslin2.R": MAASLIN2_ENV_NAME,
    "run_nmds.R": MAASLIN2_ENV_NAME,
    "run_maaslin2_longitudinal.R": MAASLIN2_ENV_NAME,
}


def r_script_env(script_name: str) -> str:
    """Return the conda env name for a given R script filename."""
    return _R_SCRIPT_ENV_MAP.get(script_name, CONDA_ENV_NAME)


def conda_cmd(args: list[str], env_name: str | None = None) -> list[str]:
    """Wrap a command to run inside a conda environment via conda run."""
    env = env_name or CONDA_ENV_NAME
    return ["conda", "run", "-n", env, "--no-capture-output"] + args

# --- Server ---
HOST = "0.0.0.0"
PORT = int(os.environ.get("PORT", 7000 + os.getuid()))  # env override for Docker
DEBUG = True

# --- CPU ---
CPU_COUNT = os.cpu_count() or 1
MAX_THREADS = max(1, CPU_COUNT - 1)  # leave 1 core free
# R tools (DA, longitudinal) start one R worker per thread; beyond ~32 the
# startup cost outweighs the gain, so this is only their default, not a cap.
R_DEFAULT_THREADS = min(32, MAX_THREADS)


def picrust2_default_threads() -> int:
    """RAM-aware PICRUSt2 default: each HSP worker uses ~2 GB."""
    try:
        total_ram_gb = os.sysconf("SC_PAGE_SIZE") * os.sysconf("SC_PHYS_PAGES") / (1024 ** 3)
    except (ValueError, OSError):
        total_ram_gb = 8
    return max(1, min(MAX_THREADS, int((total_ram_gb - 4) / 2)))


# --- Pipeline defaults ---
DADA2_DEFAULTS = {
    "trim_left_f": 0,
    "trim_left_r": 0,
    "trunc_len_f": 0,
    "trunc_len_r": 0,
    "min_overlap": 12,
    "threads": MAX_THREADS,
}

LONGREAD_DADA2_DEFAULTS = {
    "min_len": 1000,
    "max_len": 1600,
    "max_ee": 10,
    "band_size": 32,
    "threads": MAX_THREADS,
}
